# 1. Namespace for the Game
apiVersion: v1
kind: Namespace
metadata:
  name: game2048
---
# 2. Deployment for the 2048 Game
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2048
  namespace: game2048
  labels:
    app.kubernetes.io/name: app2048
spec:
  replicas: 5 # As specified in the video
  selector:
    matchLabels:
      app.kubernetes.io/name: app2048
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app2048
    spec:
      # This Fargate profile selector is matched by the Fargate profile in main.tf
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: container-2048
          #image: public.ecr.aws/l6m2u8k2/2048-game:latest # Image used in the tutorial's linked YAML
          image: 082088055283.dkr.ecr.ap-south-1.amazonaws.com/my-ecr-repo2025:latest
          
          ports:
            - containerPort: 80
---
# 3. Service to Expose the Pods Internally
apiVersion: v1
kind: Service
metadata:
  name: service-2048
  namespace: game2048
  labels:
    app.kubernetes.io/name: app2048
spec:
  # ClusterIP or NodePort is fine, as Ingress will handle external traffic
  type: ClusterIP 
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: app2048
---
# 4. Ingress to Provision the ALB
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-2048
  namespace: game2048
  annotations:
    # Use the AWS Load Balancer Controller
    kubernetes.io/ingress.class: alb
    # Create an internet-facing ALB
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Specify the name of the target group
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-2048
                port:
                  number: 80